name: Deploy

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2-beta
      with:
          node-version: 12
    
    - name: Running Tests
      run:  npm run test
      
    - name: Installing dependencies
      run: npm install
      
    
            
    - name: Building React App
      run: CI=false npm run build
            
    - name: Deploying to Netlify
      uses: nwtgck/actions-netlify@v1.1
      with:
        publish-dir: './build'
        production-deploy: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
